#server:
#  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/match_manage
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  mail:
    host: smtp.163.com
    username: gsljavastudy@163.com
    password: GDYPHWRUKYVBBYVR
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update